# Main configuration for the arbitrage bot

exchanges:
  binance:
    enabled: true
    # API credentials will be loaded from environment variables
    # e.g., BINANCE_API_KEY, BINANCE_API_SECRET
    trading_pairs:
      - "BTC/USDT"
      - "ETH/USDT"
  kraken:
    enabled: true
    # e.g., KRAKEN_API_KEY, KRAKEN_API_SECRET
    trading_pairs:
      - "BTC/USDT"
      - "ETH/USDT"
  # Add other exchanges here following the same structure
  # e.g., coinbasepro, bitfinex, etc.

arbitrage:
  # The minimum profit percentage to trigger a trade
  min_profit_threshold: 0.01
  
  # The maximum amount of capital (in USDT) to use for a single arbitrage trade
  max_trade_size: 100.0
  
  # The maximum slippage percentage allowed when executing orders
  max_slippage: 0.1

risk:
  # An overall stop-loss limit in USDT. The bot will stop if total losses exceed this.
  emergency_stop_loss: 500.0
  
  # The maximum number of concurrent open trades
  max_open_trades: 3

logging:
  level: "INFO" # e.g., DEBUG, INFO, WARNING, ERROR
  file: "arbitrage_bot.log" 