# Main configuration for the arbitrage bot

exchanges:
  binance:
    enabled: true
    # API credentials will be loaded from environment variables
    # e.g., BINANCE_API_KEY, BINANCE_API_SECRET
    symbols:
      # Original pairs
      - "CRV/USDT"
      - "TRB/USDT"
      # High-opportunity pairs (small/medium cap)
      - "PEPE/USDT"    # Meme coin with high volatility
      - "1INCH/USDT"   # DEX aggregator token
      - "UNI/USDT"     # Uniswap token
      # - "MATIC/USDT"   # Polygon Layer2
      - "LINK/USDT"    # Chainlink oracle
      - "DOGE/USDT"    # Popular meme coin
      # Lower priority but stable
      - "ADA/USDT"     # Cardano
      - "DOT/USDT"     # Polkadot
  gateio:
    enabled: true
    # e.g., GATEIO_API_KEY, GATEIO_API_SECRET
    symbols:
      # Original pairs
      - "CRV/USDT"
      - "TRB/USDT"
      # High-opportunity pairs
      - "PEPE/USDT"
      - "1INCH/USDT"
      - "UNI/USDT"
      # - "MATIC/USDT"
      - "LINK/USDT"
      - "DOGE/USDT"
      # Lower priority
      - "ADA/USDT"
      - "DOT/USDT"
  # Add other exchanges here following the same structure
  # e.g., coinbasepro, bitfinex, etc.

arbitrage:
  # The minimum profit percentage to trigger a trade
  min_profit_threshold: 0.01
  
  # The maximum amount of capital (in USDT) to use for a single arbitrage trade
  max_trade_size: 100.0
  
  # The maximum slippage percentage allowed when executing orders
  max_slippage: 0.1
  
  # Event-driven scanning configuration
  scan_cooldown_ms: 500  # Minimum milliseconds between scans to avoid spam
  
  # Legacy polling interval (only used for emergency stop checks now)
  scan_interval_s: 30

risk_management:
  # The maximum number of concurrent open trades
  max_open_trades: 5
  
  # Emergency stop-loss percentage (will trigger when PnL drops below this percentage)
  emergency_stop_loss_pct: 10.0
  
  # File to store PnL tracking data
  pnl_file: "pnl_report.json"

logging:
  level: "DEBUG" # Can be DEBUG, TRACE, INFO, WARNING, ERROR, CRITICAL
  file: "arbitrage_bot.log" 
