[project]
name = "inter_ex_arbitrage"
version = "0.1.0"
description = "A high-performance, low-latency cryptocurrency arbitrage bot."
requires-python = ">=3.8"
dependencies = [
    "ccxt[async]"
]

[project.optional-dependencies]
dev = [
    "uv",
] 